### ISSUE TITLE
Upload data

### ISSUE THREAD

**Issue by Boris-Droz** [pmartR/malbacR#5]
Hi, 
Nice package and certainly helpful.
I run through the example but have hard time to find a way to upload my data on the function.
Could you help me to navigate through? Do you have a function that load your data into the function from two csv file (on data and the next the datainfo).
Thank you

**Comment by leac176** [comment]
Hello, malbacR, works in tandem with another R package, pmartR (https://pmartr.github.io/pmartR/). Within pmartR, there are several different functions for creating omics objects based on the type of molecule being analyzed (e.g., as.lipidData() for lipids, as.metabData() for metabolites, etc.) 

These functions require 6 main arguments: e_data, edata_cname, f_data, fdata_cname, e_meta, and emeta_cname. The following vignette is helpful for creating omics objects in both pmartR and malbacR (https://pmartr.github.io/pmartR/articles/Data_Object_Creation.html)

Thanks!

**Comment by Boris-Droz** [comment]
Great thank you. Problem solve.
