### ISSUE TITLE
output of bc_tiger,bc_scrrf and bc_qcrfsc dont have associated QC

### ISSUE THREAD

**Issue by Boris-Droz** [pmartR/malbacR#6]
Hi Damon, 
I run some data using all algorithm provide in malbacR.
Inspecting the output result, it appear to me that the  output from bc_tiger,bc_scrrf and bc_qcrfsc don't have associated QC in the e_data and f_data where for all other algorithm there still are present.
I am just wonder if there is a way to keep the QC data in the output fro those.
I want to use QC output data to check performance of the different algorithm to choose the best.
Thank you

**Comment by leac176** [comment]
Hello, some functions (namely QC-RFSC and QC-RLSC) do have an argument that can be used called "keep_qc" which by default is set to FALSE, but can be changed to TRUE. By setting it TRUE, this leaves the QC samples in the final output. While our goal would to be have this for every QC-based method, some internal functions from other packages that are used for malbacR (namely TIGER and WaveICA) automatically remove the QC samples in the process so the other QC-based methods do not currently have that same ability. We are in the process of seeing what can be reasonably accomplished for those other methods.

**Comment by Boris-Droz** [comment]
Okay thanks. Looking forward the next version of the package with this 👍
